### ISSUE TITLE
Would you like to move this repo into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app-router#2]
Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js? 

This would reduce bus factor as currently only @nickcoury can add contributors to this project. By moving org admins can at least add new people, currently that's @matt-kruse and myself.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by nickcoury** [comment]
Sounds great, transfer initiated.

**Comment by dblock** [comment]
Done, it's here! @nickcoury you're still admin and what not.

**Comment by dblock** [comment]
@nickcoury You might want to add me and @matt-kruse to npm as well, just in case.

**Comment by nickcoury** [comment]
Ok, you should both have access now.
