### ISSUE TITLE
can we use multiple YES intens on different routes?

### ISSUE THREAD

**Issue by pYr0x** [alexa-js/alexa-app-router#8]
unfortunately the readme does not answer this question.
can we register multiple AMAZON:YES intents like:

````
'/summary': {
        'AMAZON.NoIntent': menuHandler,
        'AMAZON.YesIntent': summaryHandler
},
'/choose': {
        'AMAZON.NoIntent': menuHandler,
        'AMAZON.YesIntent': chooseHandler
}
```

**Comment by nickcoury** [comment]
Yes, you can.  In this case, if you have set the router to `/summary` and the user responds with `AMAZON.YesIntent`, it will run the summaryHandler. If you set the router to `/choose` and the user responds with `AMAZON.YesIntent`, it will run the chooseHandler.
